import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/custom/header";
import UserContextProvider from "@/components/context/UsercontextProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { TooltipProvider } from "@radix-ui/react-tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserContextProvider>
          <SidebarProvider>
            <TooltipProvider>
              <div className="min-h-screen flex w-full">
                <div className="flex-1 flex flex-col min-h-screen">
                  <Header></Header>
                  <main className="flex-1 p-4 md:p-6 overflow-auto">
                    {children}
                  </main>
                </div>
              </div>
            </TooltipProvider>
          </SidebarProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
